### ISSUE TITLE
play animations once

### ISSUE THREAD

**Issue by mustafarenkci** [emrade/flutter_cool_alert#1]
Is there a way to prevent infinity animations? Every alert icons plays infinity. I want them to play only once.
@emrade

**Comment by emrade** [comment]
Hi @mustafarenkci, i just added new customization properties to help add your own flareAsset you can use the version 1.0.2.
So you can customize your own flareAsset without a loop. 

Much later, when i have enough time, i will try to customize some flare assets without loops so please bear with me.

or if you prefer lottie you can use lottieAsset and pass a path of your lottie json file.

I hope this helps you.

cool_alert: ^1.0.2.
