### ISSUE TITLE
Run Animation only one time?

### ISSUE THREAD

**Issue by w0rsti** [emrade/flutter_cool_alert#11]
Is there a way to change the Widget, so we can decide if we an endless loop of the animation or that the animation should run only once?

**Comment by emrade** [comment]
@w0rsti Hi, to solve the issue you raised, i added a new attribute called "loopAnimation" which is of type boolean, but default it is set to false.

Basically it determines if the animation should loop or not, when false it won't loop, but when true it would. Thanks for the suggestion.

Check out the latest version of the package
