### ISSUE TITLE
Loading alert close on completion of an asynchronous call

### ISSUE THREAD

**Issue by inkersgithub** [emrade/flutter_cool_alert#12]
I want to use Loading Alert while calling an API similar to progress dialog. Is it possible?

**Comment by emrade** [comment]
Yes it is. Something like
``` 
void load() async{

CoolAlert.show( context: context, type: CoolAlertType.loading);
await apiLoadingAsync(); // Your API call
Navigator.pop(context); // This closes the dialog
}
```

**Comment by MuhammadDicky** [comment]
Is good but there is no option to prevent user to close dialog when user click outside dialog or push back button
