### ISSUE TITLE
Flutter Web: how can i control the width of the popup?

### ISSUE THREAD

**Issue by rohitranjan1991** [emrade/flutter_cool_alert#17]
In Web, the popup Dialog is just Expanded to the full width of the screen which is not looking good. How can I control the width of the popup?

**Comment by emrade** [comment]
Hi @rohitranjan1991, cool alert has a property called ```width```. You can use that to adjust the width as you'd like.

I hope that answers your questions. Feel free to re-open the issue if it does not.
