### ISSUE TITLE
Remove the animation at top

### ISSUE THREAD

**Issue by wmhseir3** [emrade/flutter_cool_alert#18]
hi, this plugin is great. 
however, i would like to remove the animation at top.
is there any option to make this happen?
thanks.
william

**Comment by emrade** [comment]
Hi @wmhseir3 there is currently no way to remove the animation entirely, but its possible to make the animation run only once. There is a property called ```loopAnimation```. When set to false, only shows the animation once and that's it.

Maybe on a later version i will provide still image options....
