### ISSUE TITLE
Not close dialog when clicking on ok button

### ISSUE THREAD

**Issue by ankushmishra2903-official** [emrade/flutter_cool_alert#19]
This is my code
```
CoolAlert.show(
      context: context,
      type: CoolAlertType.success,
      title: title,
      text: desc,
      onConfirmBtnTap: path != null ? () async{
          Navigator.pushNamed(context, path);
      } : null,
```
when i pass null to path  it will working fine but when i pass it any thing then dialog will not close 

even i tried ```    Navigator.pop(context);      ```  before push then same nothing happen and when i add it after push it will push and came to same page but dialog is still open even i tried to ```   return null;   ```  but this will also not close 

can anyone tell me how i close it;

**Comment by emrade** [comment]
Hi @ankushmishra2903-official, the package was configured so by default it closes when you tap the confirm button, if you override the onConfirmBtnTap tap functionality, then you'd have to close the dialog yourself. So you could do something like

```
CoolAlert.show(
      context: context,
      type: CoolAlertType.success,
      title: title,
      text: desc,
      onConfirmBtnTap: path != null ? () async{
           Navigator.pop(context); // <-- This here closes the dialog before your other functions run
          Navigator.pushNamed(context, path);
      } : null,
      
```

**Comment by ankushmishra2903-official** [comment]
> Hi @ankushmishra2903-official, the package was configured so by default it closes when you tap the confirm button, if you override the onConfirmBtnTap tap functionality, then you'd have to close the dialog yourself. So you could do something like
> 
> ```
> CoolAlert.show(
>       context: context,
>       type: CoolAlertType.success,
>       title: title,
>       text: desc,
>       onConfirmBtnTap: path != null ? () async{
>            Navigator.pop(context); // <-- This here closes the dialog before your other functions run
>           Navigator.pushNamed(context, path);
>       } : null,
>       
> ```

I do same  but dialog not close and error also not showing don't know how

**Comment by felixjunghans** [comment]
I had exactly the same problem. I was able to fix it by using `Navigator.of(context, rootNavigator: true).pop();.`
