### ISSUE TITLE
Small bug with dismissing alert

### ISSUE THREAD

**Issue by karmarcharger** [emrade/flutter_cool_alert#21]
With CoolAlertType.info, if you do not have anything assigned to the OnConfirmBtnTap: and you have the autoCloseDuration: tag active, if a use tries to press the OK button, it will dismiss the alert, then the autoCloseDuration would dismiss the current webpage since the alert is already dismissed, which will result in a blank page if the page was the base page.

Removing autoCloseDuration solves this issue, would be nice if the button can be disabled for the alerts so that its possible to just have the tick animation fade away after being displayed like a normal alert.

**Comment by emrade** [comment]
Thanks for pointing this out. Releasing a fix
