### ISSUE TITLE
Can move confirm button to left side?

### ISSUE THREAD

**Issue by NoNSteP** [emrade/flutter_cool_alert#25]
how can i move confirm button to left side.
if i change text in confirmBtnText to cancel and cancelBtnText to confirm i also can't change cancel button background color to green. or i should create custom button on all widget.
Sorry for my bad language.

**Comment by emrade** [comment]
Hello @NoNSteP, i just introduced a new property called `reverseBtnOrder`, set it to true is you want to switch the button positions.
