### ISSUE TITLE
I don't know if this is a problem or not, it's just not pleasing to the eye when running flutter

### ISSUE THREAD

**Issue by ptrnov** [emrade/flutter_cool_alert#31]
I get the below message when running "cool_alert", I don't know if it has anything to do with the "animation pack", when running everything works fine, but this message looks unsightly, and I don't know if it will interrupt the release and compilation.

/opt/homebrew/Caskroom/flutter/2.5.3/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-3.0.2/lib/flare_render_box.dart:167:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/opt/homebrew/Caskroom/flutter/2.5.3/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance?.cancelFrameCallbackWithId(_frameCallbackID);

**Comment by Erchil66** [comment]
Better to fork this project and try to remove the !/? signs
 if you are using latest flutter version

**Comment by j3g** [comment]
anyone find a fork of this project that fixes this issue, and has other updates?

**Comment by matwright** [comment]
I created a fork a while back with a few other fixes.

https://pub.dev/packages/cool_alert_two

If you want to add these further bugs there, I can take a look.

I was using this component in a few projects, but this repo hasn't been responsive to PR's for a loooong time.

**Comment by emrade** [comment]
Sorry guys, been pretty busy. I will work on the updates and merge in the PRs this weekend.

**Comment by emrade** [comment]
Sorry for the delay. @j3g @Erchil66  @ptrnov. I have fixed that issue.
