### ISSUE TITLE
Dismiss dialog without clicking anything

### ISSUE THREAD

**Issue by glennmichaelmejias** [emrade/flutter_cool_alert#7]
Dismiss dialog without clicking anything

**Comment by emrade** [comment]
Hello @glennmichaelmejias if you want to dismiss the dialog without clicking, the create a timer that closes the dialog after a set duration. I will add it to the todo as a possible feature for later

**Comment by emrade** [comment]
@glennmichaelmejias With the new version i added a new attribute "autoCloseDuration" which is of type Duration, when you set a value to it, it will auto close based on your setting, if it is null, you will have to close it manually
