### ISSUE TITLE
can't style the text content

### ISSUE THREAD

**Issue by kareemX** [emrade/flutter_cool_alert#9]
hi there, first I wanna thank you for this amazing plugin,
I wanna add many lines of text all aligned to left and apply different styles to each one,
in order to o this the 'text' attribute should take a Widget instead of String so that I can create RichText.

**Comment by emrade** [comment]
Hi @kareemX, in the later version a new attribute "widget" has been added, it's of type Widget. So you could set your custom content inside it. You can check the example page for more details.
